### ISSUE TITLE
문단 문법에서 하단 가로선 문제

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki-theme-paper#3]
![bug image](http://i.imgur.com/K5yoz79.png)

이미지와 같이 오른쪽에 표가 있을 경우 문단 하단의 가로선이 표를 침범합니다(하단은 기존 색이 흐려서 임의로 css를 수정했습니다).

이 또한 css 문제로 보입니다만 확인 부탁드립니다.

**Comment by wkpark** [comment]
음.. 개발판에서 이미 고친 부분인데 커밋을 안했나보네요..

**Comment by NbverHub** [comment]
언제쯤 커밋될까요?

**Comment by wkpark** [comment]
테이블 배경색을 세팅하는 방식으로 고쳤습니다~

**Comment by NbverHub** [comment]
아, 고쳐졌네요. 감사합니다!
