### ISSUE TITLE
1.2.5-RC9 업데이트

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki-theme-paper#4]
1.2.5-RC9 이후 $menu 관련해서 문제가 있는듯 합니다. 모바일에서 $menu 설정대로 나오지 않고 frontpage와 RecentChange만 표시되네요

**Comment by wkpark** [comment]
모바일의 경우 가로 너비가 맞지 않아서 메뉴가 넘치는 경우가 있는데,

```
$menu=array('FrontPage'=>1,'FindPage'=>4,'TitleIndex'=>3,'RecentChanges'=>2,'UserPreferences'=>'')
```

위에서 메뉴를 설정하듯이 모바일의 경우에는

```
$mobile_menu=array('FrontPage'=>....);
```

설정을 넣어주시면 됩니다.

이 부분은 `$mobile_menu`를 정의하지 않았을 경우에는 `$menu` 설정값을 쓰도록 고쳐두겠습니다~

**Comment by wkpark** [comment]
아 그리고 이것은 테마 문제가 아니라 모니위키 버그입니다.

**Comment by NbverHub** [comment]
아, 그렇군요. 다른 테마에서는 정상적으로 나오길래(monistrap 등) 테마 문제인 줄 알았네요.
